apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: svd-stage-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: svd-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/svd-stage/env/overlays
    repoURL: https://github.com/TomWeiWei/svd-ocp-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
