apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-svd-ocp-app-taxi
  name: svd-dev-app-svd-ocp-app-taxi
  namespace: openshift-gitops
spec:
  destination:
    namespace: svd-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/svd-dev/apps/app-svd-ocp-app-taxi/overlays
    repoURL: https://github.com/TomWeiWei/svd-ocp-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
