apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: svd-ocp-app-taxi
    app.kubernetes.io/part-of: app-svd-ocp-app-taxi
  name: svd-ocp-app-taxi
  namespace: svd-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: svd-ocp-app-taxi
      app.kubernetes.io/part-of: app-svd-ocp-app-taxi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: svd-ocp-app-taxi
        app.kubernetes.io/part-of: app-svd-ocp-app-taxi
    spec:
      containers:
      - image: quay.io/tomweiwei/ocp-taxi:master-7a1e8e4249808ad0c42ae698bd7f4f9d2c46ac82
        imagePullPolicy: Always
        name: svd-ocp-app-taxi
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
